@echo OFF
color b
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.                   .mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.                       `-+ymMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdsydmNNNMMMMMMMMMMMMMMM.     `.odMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.       omMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmM.       `:hMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNN.        `/mMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMhmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:          `oMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMd N//MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh:          :mMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMs  `mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMs          .mMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMy   +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN\  |MMo          .mMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMd`    dMMMhMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\_|hMMm          MMNMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMM-     MMM++MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM/`          oMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMy      MMd dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmo.        `NMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMM:      mMs mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMms.       yMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMM       oMo hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNs.     /MMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMm       `mo /MMMN+MMMMMMMMMMMMMMMMMMMMdooosydmNMMMMMMMMMMm+    :MMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMm        -s  yMMN`hMMMMMMMMMMMMMMMMMMM+      `-:oydNMMMMNmo    -MMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMN         .  `hMM/`hMMMMMMMMMMMMMMMMMMN/          `-/o+/-`     :MMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMM-            `sNN.`sNMMMMMMMMMMMMMMMMMMy.                     sMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMs              :hd. :dMMMMMMMMMMMMMMMMMMN+                    mMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMN.               :o- `/dNMMMMMMMMMMMMMMMMMy`                 +MMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMy                 `    :smNMMMMMMMMMMMMMMMh`               .NMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMo                       `-ohmNMMMMMMMMMMMMy              `dMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMM+                          `-/oymNMMMMMMMM/            `hMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMo`                             `-+dMMMMMMm           .dMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMh.                                :dMMMMM.         /NMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMNo`                                +NMMM-       .yMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMm+`                               /MMM.     .sNMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMmo.                              oMd   `:yNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd+.                           `N:`-smMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmy/.`                     `:dhNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdyo+:-.      ..-/+shmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
echo MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
pause >nu1 
:prompt

node .